-- Create user_progress_photos table
CREATE TABLE IF NOT EXISTS public.user_progress_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  photo_type VARCHAR(10) NOT NULL CHECK (photo_type IN ('front', 'side')),
  photo_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create index on user_id for faster queries
CREATE INDEX IF NOT EXISTS idx_user_progress_photos_user_id ON public.user_progress_photos(user_id);

-- Create index on photo_type for filtering
CREATE INDEX IF NOT EXISTS idx_user_progress_photos_photo_type ON public.user_progress_photos(photo_type);

-- Enable Row Level Security
ALTER TABLE public.user_progress_photos ENABLE ROW LEVEL SECURITY;

-- Create policy to allow users to view their own progress photos
CREATE POLICY "Users can view own progress photos"
  ON public.user_progress_photos FOR SELECT
  USING (auth.uid() = user_id);

-- Create policy to allow users to insert their own progress photos
CREATE POLICY "Users can insert own progress photos"
  ON public.user_progress_photos FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Create policy to allow users to update their own progress photos
CREATE POLICY "Users can update own progress photos"
  ON public.user_progress_photos FOR UPDATE
  USING (auth.uid() = user_id);

-- Create policy to allow users to delete their own progress photos
CREATE POLICY "Users can delete own progress photos"
  ON public.user_progress_photos FOR DELETE
  USING (auth.uid() = user_id);
